---
# handlers file for role-snmp

- name: "Restart snmpd service"
  tags:
    - install
    - install_snmp
  ansible.builtin.service:
    name: snmpd
    state: restarted

- name: "Restart snmp win service"
  tags:
    - install
    - install_snmp
  ansible.windows.win_service:
    name: "SNMP"
    state: restarted
