---
# handlers file for role-snmp

- name: restart snmpd service
  service:
    name: snmpd
    state: restarted

- name: restart snmp win service
  win_service:
    name: "SNMP"
    state: restarted
